---
title: "Ideas for Improvement"
output: html_document
---

Feature Ideas for automodel:
  
Variable transformation option for outcomes (box-cox? What I already know)
show all output, or stop on a violated assumption (boolean option, but hand checking assumptions makes this hard, may not be doable)
output for glm logistic regression, with compact output formula (done but need some extras)
spss output options (saving variables, different plot) maybe collapsed into one 'verbose' option. (not sure what to do with this at the moment)

To do list:
bookkeeping tasks:
Clear up warnings and stuff from package check output (got everything but the latex errors stuff)
get file exclude list clear
update vignette

code tasks:
revise and refactor if possible, all the functions (not sure what I meant by this, but it seems quite general)
Eliminate the use of the modified lmSupport function, by replacing it with my own attempt to replicate that object creation
Check the accuracy of partial regression plots (in fact, compare 1-1 with spss output for the same model) (will do some comparative checks with SPSS when all's said and done)
Allow to save as a variable (this should not be hard)
Allow user to choose more Verbose names to be used in lieu of the column names for the output

Logistic regression needs
classification table: nothing premade exists, cutpoint must be specified, can be optimized but it is unclear how one can do this
pseudo R^2: McFadden's (recommended online but need another source), Nagelkerke's (offered by SPSS; R package: ), Cox-Snell (offered by SPSS; R package: )


Input checking: How to do it, how important is it, etc?

Final to do list before cran submission
finish binary logistic regression output
(add wald test and p values to coefficient table)
(is there a way to make classification table look right? Is there an xtable method for table()?)
Read submission guidelines
track down latex errors in pdf manual
run some more tests with real data to make sure that I'm not gonna run into problems with missing data, other weird stuff, etc.
add input checking to avoid these problems
revise and clean up everything so that there is nothing extraneous in the package build or in the actual important files.  Consider dividing the main file into at least 2 if not 3 files.


MEGA TASK ::::::
IS THERE A WAY TO MAKE KNITR OUTPUT DOCUMENTS PRETTY??????  
IE. In lieu of the standard output tables in the code output windows, can I have a nicely formatted latex-y table ?
(this is the thing that could become something big..., use to up my github profile)
AP paragraph option?  Template with blanks to fill in with data values for addition to output document


SIDE NOTE:
IS there a knitr equivalent for python?  Is it just the ipython notebook?  Do they need an improved version?
